name: Selenium Tests

on: [push, pull_request]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Start all services
        run: sudo docker-compose -f "docker-compose.yml" up -d --build

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Run selenium tests
        run: npm run selenium-test

      - name: Stop all services
        run: sudo docker-compose -f "docker-compose.yml" down
